client/Client/Models/Certificate.cs
namespace Client.Models;

public class Certificate
{
    public int Id { get; set; }
    public Guid Name { get; set; }
    public string Subject { get; set; }
    public string Issuer { get; set; }
    public string KeyPairs { get; set; }
    public byte[] Data { get; set; }
    public string FilePath { get; set; }
    public DateTime ValidFrom { get; set; }
    public DateTime ValidUntil { get; set; }
    public DateTime CreationDateTime { get; set; }
    public bool Deleted { get; set; }
}

client/Client/Models/ErrorViewModel.cs
namespace Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

client/Client/Controllers/CertificatesController.cs
using Client.ApiServices;
using Client.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

namespace Client.Controllers
{
    public class CertificatesController : Controller
    {
        private readonly ICertificateApiService _certificateApiService;

        public CertificatesController(ICertificateApiService certificateApiService)
        {
            _certificateApiService = certificateApiService;
        }

        // GET: Certificates
        public async Task<IActionResult> Index()
        {
            await LogTokenAndClaims();
            return View(await _certificateApiService.GetAllCertificatesAsync());
        }

        public async Task LogTokenAndClaims()
        {
            var identityToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);

            Console.WriteLine($"Identity token: {identityToken}");

            foreach (var claim in User.Claims)
            {
                Console.WriteLine($"Claim types: {claim.Type} - Claim value: {claim.Value}");
            }
        }

        // GET: Certificates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return View();
        }

        // GET: Certificates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Certificates/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Name,Subject,Issuer,KeyPairs,Data,FilePath,ValidFrom,ValidUntil,CreationDateTime,Deleted")]
            Certificate certificate)
        {
            return View();
        }

        // GET: Certificates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            return View();
        }

        // POST: Certificates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Name,Subject,Issuer,KeyPairs,Data,FilePath,ValidFrom,ValidUntil,CreationDateTime,Deleted")]
            Certificate certificate)
        {
            return View();
        }

        // GET: Certificates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            return View();
        }

        // POST: Certificates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            return View();
        }
    }
}

client/Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

client/Client/Views/Certificates/Create.cshtml
@model Client.Models.Certificate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Certificate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Issuer" class="control-label"></label>
                <input asp-for="Issuer" class="form-control" />
                <span asp-validation-for="Issuer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KeyPairs" class="control-label"></label>
                <input asp-for="KeyPairs" class="form-control" />
                <span asp-validation-for="KeyPairs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidUntil" class="control-label"></label>
                <input asp-for="ValidUntil" class="form-control" />
                <span asp-validation-for="ValidUntil" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDateTime" class="control-label"></label>
                <input asp-for="CreationDateTime" class="form-control" />
                <span asp-validation-for="CreationDateTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Deleted" /> @Html.DisplayNameFor(model => model.Deleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

client/Client/Views/Certificates/Delete.cshtml
@model Client.Models.Certificate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Certificate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Issuer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Issuer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KeyPairs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KeyPairs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidFrom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidFrom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidUntil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidUntil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

client/Client/Views/Certificates/Details.cshtml
@model Client.Models.Certificate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Certificate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Issuer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Issuer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KeyPairs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KeyPairs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidFrom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidFrom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidUntil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidUntil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deleted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

client/Client/Views/Certificates/Edit.cshtml
@model Client.Models.Certificate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Certificate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Issuer" class="control-label"></label>
                <input asp-for="Issuer" class="form-control" />
                <span asp-validation-for="Issuer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KeyPairs" class="control-label"></label>
                <input asp-for="KeyPairs" class="form-control" />
                <span asp-validation-for="KeyPairs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidUntil" class="control-label"></label>
                <input asp-for="ValidUntil" class="form-control" />
                <span asp-validation-for="ValidUntil" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDateTime" class="control-label"></label>
                <input asp-for="CreationDateTime" class="form-control" />
                <span asp-validation-for="CreationDateTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Deleted" /> @Html.DisplayNameFor(model => model.Deleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

client/Client/Views/Certificates/Index.cshtml
@model IEnumerable<Client.Models.Certificate>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issuer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KeyPairs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValidFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValidUntil)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Issuer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KeyPairs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValidFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValidUntil)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deleted)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

client/Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

client/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Certificates" asp-action="Index">Certificates</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>